---
id: OpenXchange
name: OpenXchange
full: Open-Xchange client library
description: A library to interact with Open-Xchange servers.
list: dev
type: library
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 2.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/date: ^3
      horde/http: ^3
      horde/perms: ^3
      horde/url: ^3
